#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

.config/polybar/launch.sh &

nitrogen --restore &

picom -f & 

plank &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3 
bspc config window_gap              8 

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config focus_follows_pointer   true

#bspc rule -a Nitrogen           state=floating  center=true 
bspc rule -a Pavucontrol        state=floating              
bspc rule -a Lxappearance       state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a Plank layer=above manage=on border=off
