#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh &

nitrogen --restore &

picom -f &

bspc monitor -d I II III IV V

bspc config border_width         2.5
#bspc config window_gap          7

bspc config top_padding 0
bspc config left_padding 5
bspc config right_padding 5
bspc config bottom_padding 5

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a nitrogen desktop='^3'
bspc rule -a pamac-aur desktop='^4'
bspc rule -a zoom desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# border colors
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
